" Sets the color scheme in gui mode.

if has("nvim")
    GuiFont! SauceCodePro\ Nerd\ Font:h14
    GuiTabline 0
    colorscheme gruvbox
else
    set guifont=Hack\ NF:h14,consolas:h14
    colorscheme lucius
endif

" Set background to light between 7:00 and 18:30. Dark otherwise.
function! s:setbackground()
    if (strftime('%H%M') % 1830) >= 700
      set background=light
    else
      set background=dark
    endif
endfunction

" call setbackground at startup ...
call s:setbackground()
" ... and again when inactive.
autocmd CursorHold * nested call s:setbackground()

" Default size is a little bigger than 80 columns to accomodate line numbers.
set columns=100
set lines=60

