set -o vi

export XDG_CONFIG_HOME=${HOME}/.config

. $XDG_CONFIG_HOME/aliases.bashrc
. $XDG_CONFIG_HOME/vars.bashrc

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_DESCRIBE_STYLE="branch"
export GIT_PS1_SHOWCOLORHINTS=true

. $XDG_CONFIG_HOME/prompt.bashrc

# if [[ -n "$PS1" ]] && [[ -z "$TMUX" ]]; then
  # tmux attach-session -t default || tmux new-session -s default
# fi

# Enable SSO via keychain and ssh-agent
[[ -f ${HOME}/.ssh/id_ecdsa ]] && eval `keychain -q --eval --agents ssh id_ecdsa`
