export XDG_CONFIG_HOME=${HOME}/.config

# Firm specific settings, see also firm-post below.
[[ -f ${XDG_CONFIG_HOME}/firm-pre.bashrc ]] && . ${XDG_CONFIG_HOME}/firm-pre.bashrc

# Unique Bash version check
if ((BASH_VERSINFO[0] < 4))
then
  echo "sensible.bash: You need at least bash-4.0 or some options will not work correctly."
fi

. $XDG_CONFIG_HOME/opts.bashrc
. $XDG_CONFIG_HOME/history.bashrc
. $XDG_CONFIG_HOME/aliases.bashrc
. $XDG_CONFIG_HOME/vars.bashrc

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_DESCRIBE_STYLE="branch"
export GIT_PS1_SHOWCOLORHINTS=true

. $XDG_CONFIG_HOME/prompt.bashrc

# Enable SSO via keychain and ssh-agent.
[[ -f ${HOME}/.ssh/id_ecdsa ]] && eval `keychain -q --eval --agents ssh id_ecdsa`

# Firm specific settings, see also firm-pre above.
[[ -f ${XDG_CONFIG_HOME}/firm-post.bashrc ]] && . ${XDG_CONFIG_HOME}/firm-post.bashrc

# Set the window title to the hostname by default so it shows in tmux. See
# aliases.bashrc for the title alias.
[[ $(which hostname) ]] && set-title @$(hostname)
