" Sets the color scheme in gui mode.
colorscheme lucius

if has("nvim")
    GuiFont! Source\ Code\ Pro:h12
    GuiTabline 0
else
    set guifont=source\ code\ pro:h14,consolas:h14
endif

" Default size is a little bigger than 80 columns to accomodate line numbers.
set columns=120
set lines=40

" Activate sunset to automate switch between dark and light mode.
call plug#load('Sunset')

